[package]
name = "ba7c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ba7c"
path = "src/main.rs"

[lib]
name = "ba7c"
path = "src/lib.rs"

[dependencies]
